packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  tree-sitter-javascript: true
  tree-sitter-python: true
  tree-sitter-typescript: true
  unrs-resolver: true

